### PR TITLE
Issue 21 resolving implicit circular dependency

### PR DESCRIPTION
**Pull request by PRIESt512**
@ Lazy solution is the best solution to the problem #21

### CODE REVIEW

**Review by Chessray — COMMENTED** [review]
I wonder if we can provide some test case that shows the error... - maybe as an example (or an addition to the existing ones) rather than a straightforward test?

**Comment by PRIESt512** [comment]
Yes agree with you. I will think about such a test. In it, you need to raise the completely spring context and override the default injection method, which ignores BeanCurrentlyInCreationException.

**Comment by Chessray** [comment]
I've merged this into a branch for now while I'm trying to come up with a test based on the original example project. No luck so far.

**Comment by PRIESt512** [comment]
Can't reproduce the problem?

**Comment by Chessray** [comment]
Rather it doesn't seem to solve the issue. 😕  Have a look at the [branch](https://github.com/mapstruct/mapstruct-spring-extensions/tree/issue21-implicit-cyclical-dependency) for yourself if you wish.

**Comment by PRIESt512** [comment]
It’s strange. I will look later, but I remember exactly that on the project this solution worked in my project

**Pull request merged**
