### PR TITLE
Require minimum JDK 11 in line with MapStruct Core.

### PR DESCRIPTION
**Pull request by Chessray**

### CODE REVIEW

**Comment by filiphr** [comment]
@Chessray I saw this just now. Out of curiosity. Does this require Java 11 for the users or it is only for building the extension? For MapStruct we only require Java 11 to build MapStruct. However, you can still use MapStruct using Java 8

**Comment by Chessray** [comment]
Whoah, then I misread the core requirements. I'll see if and how I can adjust that to be in line wrt use.

**Comment by filiphr** [comment]
No problem. Seems like no one complained until now 😄. We do have some plans to bump the baseline of MapStruct to a newer version, but we'll announce that appropriately most likely with a bump of the major number as well (e.g. 2.0)

**Comment by Chessray** [comment]
I've been through this in various ways and will now leave it as it is. As you said, nobody has complained so far. Spring users are typically quite keen on keeping things up to date. The new Spring 6 (and Spring Boot 3 which is almost here) require Java 17 anyway.

**Comment by filiphr** [comment]
Thanks for checking it @Chessray. It is completely fine to leave it as is. I also believe that the Spring 6 and Spring Boot 3 will move the ecosystem faster towards Java 17. We'll see more and more projects doing this from next year

**Pull request merged**
