### PR TITLE
Replace generated javax.annotation.PostConstruct with jakarta

### PR DESCRIPTION
**Pull request by stickfigure**
This is compatible with Spring 6 / Spring Boot 3

### CODE REVIEW

**Comment by Chessray** [comment]
It's already being worked on; however, in order to ensure backwards compatibility, the solution must be flexible and support both packages.

**Comment by stickfigure** [comment]
Spring didn't care, I wouldn't complain if you didn't either :-)

**Comment by stickfigure** [comment]
That said, if you want compatibility with both, do you want a PR? The matter has some urgency for us, happy to write it.

**Comment by Chessray** [comment]
If you feel up to it, go ahead. :-)

**Comment by stickfigure** [comment]
Updated. If `jakarta.annotation.PostConstruct` is on the classpath, it gets used. Otherwise `javax.annotation` is generated.

I'm not quite sure how to write a test for this, but there wasn't a test for the old annotation either :-)

**Comment by stickfigure** [comment]
If this isn't backwards-compatible enough, it would be easy enough to make it check for javax.annotation first, and only generate jakarta.annotation if javax.annotation isn't present.

**Comment by filiphr** [comment]
The solution to this is not the way we should check if something exists or not. The Java annotation processor API has all the needed tools for checks like this.

The `javax.lang.model.util.Elements` utils have a method called `getTypeElement` that would return `null` if a type does not exists. I would suggest using something like that instead of class presence checks. It could happen that the class is not available in the annotation processing path, but it is there in the sources.

**Review by Chessray — CHANGES_REQUESTED** [review]
Please don't attempt to use the classpath. As @filiphr has pointed out, this is not guaranteed to deliver the desired result.

**Comment by stickfigure** [comment]
Updated

**Review by Chessray — DISMISSED** [review]

**Review by Chessray — CHANGES_REQUESTED** [review]
Sorry, i should have included this in the previous review. There _are_ tests for the deprecated annotation, although they're not explicitly labelled as such. The generator tests compare against different target files. Could you please add some accordingly?

**Comment by stickfigure** [comment]
ok, done

**Comment by stickfigure** [comment]
Any chance we can get this merged and released?

**Review by Chessray — APPROVED** [review]

**Pull request merged**
